version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo_url_shortener
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_secure_password
      MONGO_INITDB_DATABASE: urlshortener
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
